from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field
import chardet
from charset_normalizer import from_bytes

_BOM_MAP: dict[bytes, str] = {
    b'\xef\xbb\xbf':     'utf-8-sig',
    b'\x00\x00\xfe\xff': 'utf-32-be',
    b'\xff\xfe\x00\x00': 'utf-32-le',
    b'\xff\xfe':         'utf-16-le',
    b'\xfe\xff':         'utf-16-be'
}


class EncodingResult(BaseModel):
    """
    Outcome of encoding detection.

    Parameters
    ----------
    name : str
        Canonical encoding name (e.g. ``'utf-8'``, ``'latin-1'``).
    confidence : float
        Detection confidence in the range ``[0.0, 1.0]``.
    bom_detected : bool
        ``True`` when a byte-order mark was found and stripped.
    method : {'bom', 'charset_normalizer', 'chardet', 'fallback'}
        Which detector produced this result.

    Examples
    --------
    >>> result = EncodingResult(name='utf-8', confidence=0.99, method='charset_normalizer')
    >>> result.name
    'utf-8'
    >>> result.bom_detected
    False

    BOM detection always returns ``confidence=1.0``:

    >>> result = EncodingResult(name='utf-8-sig', confidence=1.0, bom_detected=True, method='bom')
    >>> result.bom_detected
    True
    """

    name: str
    confidence: float = Field(ge=0.0, le=1.0)
    bom_detected: bool = False
    method: Literal['bom', 'charset_normalizer', 'chardet', 'fallback', 'override']


class EncodingDetector:
    def __init__(
            self, 
            sample_size: int = 32768,
            default_fallback: str = 'cp1252'
        ) -> None:
        
        self.sample_size = sample_size
        self.default_fallback = default_fallback

    def detect(self, path: Path | str) -> EncodingResult:

        raw = path.read_bytes()[:self.sample_size]

        return (
            self._check_bom(raw)
            or self._try_charset_normalizer(raw)
            or self._try_chardet(raw)
        )
    
    def _check_bom(self, raw: bytes) -> EncodingResult | None:
            """
            Check whether *raw* starts with a known byte-order mark.

            Parameters
            ----------
            raw : bytes
                Raw bytes read from the file.

            Returns
            -------
            EncodingResult or None
                ``EncodingResult`` with ``confidence=1.0`` and ``bom_detected=True``
                if a BOM is found, ``None`` otherwise.
            """

            for bom, encoding in _BOM_MAP.items():
                if raw.startswith(bom):
                    return EncodingResult(
                        name=encoding, 
                        confidence=1.0, 
                        bom_detected=True, 
                        method='bom'
                    )
            return None
    
    def _try_charset_normalizer(self, raw: bytes) -> EncodingResult | None:
        """
        Try to detect encoding using charset-normalizer.

        Parameters
        ----------
        raw : bytes
            Raw bytes read from the file.

        Returns
        -------
        EncodingResult or None
            ``EncodingResult`` with ``encoding`` and ``confidence``
            derived from the chaos score, ``None`` if no candidate
            is found.
        """

        result = from_bytes(raw)
        best = result.best()
        if best is None:
            return None
        
        return EncodingResult(
            name=best.encoding,
            confidence=round(1.0 - best.chaos, 4),
            method='charset_normalizer'
        )

    def _try_chardet(self, raw: bytes) -> EncodingResult:
        """
        Try check the encoding by chardet,
        ``default_fallback`` otherwise.

        Parameters
        ----------
        raw : bytes
            Raw bytes read from the file.

        Returns
        -------
        EncodingResult
            ``EncodingResult`` with ``encoding`` and ``confidence``
            generated by chardet.
        """

        result = chardet.detect(raw, no_match_encoding=self.default_fallback)

        encoding = result.get('encoding')
        confidence = result.get('confidence')

        method = (
            'fallback'
            if (
                encoding == self.default_fallback
                and confidence < 0.05
            )
            else 'chardet'
        )

        return EncodingResult(
            name=encoding,
            confidence=confidence,
            method=method
        )